version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user_microservice_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_microservice
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - microservices

  adminer:
    image: adminer
    container_name: user_microservice_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - microservices
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  microservices:
    driver: bridge
